-- ===========================================================================
-- Dev helper: push an order to 'delivered' so the client review UI is testable.
--
-- Why this exists: no writer or agency UI has been built, so nothing in the app
-- advances an order past 'submitted'. The Approve / Request Changes buttons
-- only render on a 'delivered' order, which makes that whole branch of the
-- client UI unreachable for orders you created yourself. This stands in for the
-- writer until the planned /admin page exists.
--
-- Run it in the Supabase SQL Editor. The editor bypasses row-level security, so
-- it can insert a deliverable even though clients only hold `select` on that
-- table — do NOT widen the client policy to achieve the same thing.
--
-- Picks the most recently created order that is not already delivered.
-- Safe to run more than once; each run promotes one more order.
-- ===========================================================================

do $$
declare
  v_order uuid;
  v_title text;
begin
  select id, title into v_order, v_title
    from orders
   where status not in ('delivered', 'approved')
   order by created_at desc
   limit 1;

  if v_order is null then
    raise exception 'no eligible order found — every order is already delivered or approved';
  end if;

  insert into deliverables (order_id, version, body_md, word_count, file_name)
  values (
    v_order,
    1,
    E'## Executive Summary\n\n'
    'This draft was generated by the deliver-order.sql dev helper so the review '
    'flow could be exercised end to end. It stands in for writer output.\n\n'
    '## Key Points\n\n'
    'The **first point** carries the core argument and sets up everything that '
    'follows. Bold and *italic* markers are included so the renderer in '
    'DeliverablesViewer has something to format.\n\n'
    'The second point develops the argument with supporting detail, at enough '
    'length to show how a real paragraph wraps in the viewer.\n\n'
    '## Conclusion\n\n'
    'Approving this order should debit nothing further, flip the status badge, '
    'and reveal the download controls.',
    1180,
    'draft-v1.md'
  )
  on conflict (order_id, version) do nothing;

  update orders set status = 'delivered' where id = v_order;

  raise notice 'delivered: % (%)', v_title, v_order;
end $$;

-- Confirm, then reload the app in the browser — the running page will not pick
-- this up on its own, since the store has no realtime subscription.
select reference, title, status, updated_at
from orders
where status = 'delivered'
order by updated_at desc;
